version: "3.8"

services:
  websocket-server:
    build: .
    container_name: websocket-server
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
